# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numbas_lti', '0002_attempt_scormelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_result_sourcedid', models.CharField(default='', max_length=200)),
                ('lis_outcome_service_url', models.TextField(default='')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numbas_lti.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='scormelement',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='numbas_lti.Exam'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='numbas_lti.Resource'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scormelement',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scormelements', to='numbas_lti.Attempt'),
        ),
    ]
