# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numbas_lti', '0003_auto_20160504_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='completion_status',
            field=models.CharField(choices=[('not attempted', 'Not attempted'), ('incomplete', 'Incomplete'), ('completed', 'Complete')], default='not attempted', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='grading_method',
            field=models.CharField(choices=[('highest', 'Highest score'), ('last', 'Last attempt')], default='highest', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='include_incomplete_attempts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='numbas_lti.Resource'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
