# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0004_auto_20160505_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='grading_method',
            field=models.CharField(choices=[('highest', 'Highest score'), ('last', 'Last attempt')], default='highest', max_length=20, verbose_name='Grading method'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='include_incomplete_attempts',
            field=models.BooleanField(default=True, verbose_name='Include incomplete attempts in grading'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximum attempts per user'),
        ),
    ]
