# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0005_auto_20160505_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='scaled_score',
            field=models.FloatField(default=0),
        ),
    ]
