# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0006_attempt_scaled_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuserdata',
            name='lis_result_sourcedid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
