# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0008_auto_20160616_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
            ],
        ),
    ]
