# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0009_lticonsumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='show_incomplete_marks',
            field=models.BooleanField(default=True, verbose_name='Show score of in-progress attempts to students'),
        ),
    ]
