# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0010_resource_show_incomplete_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='report_mark_time',
            field=models.CharField(choices=[('immediately', 'Immediately'), ('oncompletion', 'On completion'), ('manually', 'Manually, by instructor')], default='immediately', max_length=20, verbose_name='When to report scores back'),
        ),
    ]
