# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0011_resource_report_mark_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiuserdata',
            name='last_reported_score',
            field=models.FloatField(default=0),
        ),
    ]
