# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0012_ltiuserdata_last_reported_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reporting', 'Reporting scores'), ('error', 'Error encountered'), ('complete', 'All scores reported')], default='reporting', max_length=10, verbose_name='Current status of the process')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time the reporting process started')),
                ('response', models.TextField(blank=True, verbose_name='Description of any error')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_processes', to='numbas_lti.Resource')),
            ],
        ),
    ]
