# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0013_reportprocess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportprocess',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='reportprocess',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Has the result of this process been dismissed by the instructor?'),
        ),
    ]
