# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0014_auto_20160718_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
