# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0015_attempt_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='report_incomplete_marks',
            field=models.BooleanField(default=True, verbose_name='Count scores for incomplete attempts?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='include_incomplete_attempts',
            field=models.BooleanField(default=True, verbose_name='Include incomplete attempts in grading?'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='show_incomplete_marks',
            field=models.BooleanField(default=True, verbose_name='Show score of in-progress attempts to students?'),
        ),
    ]
