# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0017_remove_resource_report_incomplete_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiuserdata',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='numbas_lti.LTIConsumer'),
        ),
    ]
