# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0019_lti_user_data_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='package',
            field=models.FileField(upload_to='exams/', verbose_name='Package file'),
        ),
    ]
