# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0020_auto_20161012_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarked_parts', to='numbas_lti.Attempt')),
            ],
        ),
    ]
