# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0021_remarkpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=20)),
                ('behaviour', models.CharField(choices=[('remove', 'Remove from total'), ('fullmarks', 'Award everyone full credit')], default='remove', max_length=10)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounted_parts', to='numbas_lti.Resource')),
            ],
        ),
    ]
