# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0023_attempt_broken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticonsumer',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
