# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 13:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0026_auto_20161107_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Base URL of the editor')),
                ('projects', models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')], verbose_name='IDs of projects to scan for exams')),
                ('cached_available_exams', models.TextField(blank=True, editable=False, verbose_name='Cached JSON list of available exams from this editor')),
                ('last_cache_update', models.DateTimeField(blank=True, editable=False, verbose_name='Time of last cache update')),
            ],
        ),
    ]
