# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0026_auto_20161107_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Editor name')),
                ('url', models.URLField(unique=True, verbose_name='Base URL of the editor')),
                ('cached_available_exams', models.TextField(blank=True, editable=False, verbose_name='Cached JSON list of available exams from this editor')),
                ('last_cache_update', models.DateTimeField(blank=True, editable=False, verbose_name='Time of last cache update')),
            ],
        ),
        migrations.CreateModel(
            name='EditorLinkProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the project')),
                ('description', models.TextField(verbose_name='Description of the project')),
                ('remote_id', models.IntegerField(verbose_name='ID of the project on the editor')),
                ('homepage', models.URLField(verbose_name="URL of the project's homepage on the editor")),
                ('rest_url', models.URLField(verbose_name="URL of the project on the editor's REST API")),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='numbas_lti.EditorLink', verbose_name='Editor that this project belongs to')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='rest_url',
            field=models.URLField(blank=True, default='', verbose_name="URL of the exam on the editor's REST API"),
        ),
        migrations.AddField(
            model_name='exam',
            name='retrieve_url',
            field=models.URLField(blank=True, default='', verbose_name='URL used to retrieve the exam package'),
        ),
    ]
