# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0027_auto_20161130_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorlinkproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of the project'),
        ),
    ]
