# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0027_editorlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='rest_url',
            field=models.URLField(blank=True, default='', verbose_name="URL of the exam on the editor's REST API"),
        ),
        migrations.AddField(
            model_name='exam',
            name='retrieve_url',
            field=models.URLField(blank=True, default='', verbose_name='URL used to retrieve the exam package'),
        ),
    ]
