# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0028_auto_20161201_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormelement',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
