# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0029_auto_20161220_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scormelement',
            options={'ordering': ['-time', '-counter']},
        ),
        migrations.AddField(
            model_name='scormelement',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Element counter to disambiguate elements with the same timestamp'),
        ),
    ]
