# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0030_auto_20170412_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='show_marks_when',
            field=models.CharField(choices=[('always', 'Always'), ('complete', 'When attempt is complete'), ('never', 'Never')], default='always', max_length=20, verbose_name='When to show scores to students'),
        ),
    ]
