# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 10:20
from __future__ import unicode_literals

from django.db import migrations

def show_marks(apps, schema_editor):
    Resource = apps.get_model('numbas_lti','Resource')
    for resource in Resource.objects.all():
        resource.show_marks_when = 'always' if resource.show_incomplete_marks else 'complete'

class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0031_resource_show_marks_when'),
    ]

    operations = [
        migrations.RunPython(show_marks),
    ]
