# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0032_auto_20170605_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='show_incomplete_marks',
        ),
    ]
