# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from datetime import timezone

def set_creation_times(apps, schema_editor):
    Resource = apps.get_model('numbas_lti','Resource')
    Exam = apps.get_model('numbas_lti','Exam')

    for resource in Resource.objects.all():
        first_attempt = resource.attempts.order_by('start_time').first()
        if first_attempt:
            resource.creation_time = first_attempt.start_time
            resource.save()

    for exam in Exam.objects.all():
        first_attempt = exam.attempts.order_by('start_time').first()
        if first_attempt:
            exam.creation_time = first_attempt.start_time
            exam.save()


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0034_resource_num_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('raw_score', models.FloatField()),
                ('scaled_score', models.FloatField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='numbas_lti.Attempt')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 1, 1, 1, 1, 0, tzinfo=timezone.utc), verbose_name='Time this exam was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 1, 1, 1, 1, 0, tzinfo=timezone.utc), verbose_name='Time this resource was created'),
            preserve_default=False,
        ),
        migrations.RunPython(set_creation_times,migrations.RunPython.noop),
    ]
