# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def set_current_elements(apps, schema_editor):
    Attempt = apps.get_model('numbas_lti','Attempt')
    ScormElement = apps.get_model('numbas_lti','ScormElement')

    for a in Attempt.objects.all():
        a.completion_status_element = a.scormelements.filter(key='cmi.completion_status').order_by('-time','-counter').first()
        if a.completion_status_element is not None:
            a.completion_status = a.completion_status_element.value

        a.scaled_score_element = a.scormelements.filter(key='cmi.scaled_score').order_by('-time','-counter').first()
        if a.scaled_score_element is not None:
            a.scaled_score = a.scaled_score_element.value
        a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0036_auto_20171010_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-creation_time', 'title']},
        ),
        migrations.AddField(
            model_name='attempt',
            name='completion_status_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_completion_status_of', to='numbas_lti.ScormElement'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='scaled_score_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_scaled_score_of', to='numbas_lti.ScormElement'),
        ),
        migrations.RunPython(set_current_elements,migrations.RunPython.noop),
    ]
