# Generated by Django 2.0 on 2018-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0037_auto_20171024_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='url',
            field=models.URLField(blank=True, default='', verbose_name='Home URL of consumer'),
        ),
    ]
