# Generated by Django 2.0 on 2018-05-21 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0039_auto_20180514_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestionscore',
            name='max_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attemptquestionscore',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_question_scores', to='numbas_lti.Attempt'),
        ),
    ]
