# Generated by Django 2.0 on 2018-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0040_auto_20180521_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptquestionscore',
            name='completion_status',
            field=models.CharField(default='not attempted', max_length=20),
        ),
    ]
