# Generated by Django 2.0 on 2018-05-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0041_attemptquestionscore_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
