# Generated by Django 2.0 on 2018-05-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0042_attempt_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attemptquestionscore',
            unique_together={('attempt', 'number')},
        ),
    ]
