# Generated by Django 2.0 on 2018-06-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0043_auto_20180530_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTest',
            fields=[
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='numbas_lti.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='StressTestNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('stresstest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='numbas_lti.StressTest')),
            ],
        ),
    ]
