# Generated by Django 2.0 on 2018-06-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0044_stresstest_stresstestnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='numbas_lti.Exam'),
        ),
    ]
