# Generated by Django 2.0 on 2018-10-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0045_auto_20180604_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=300)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_periods', to='numbas_lti.LTIConsumer')),
            ],
        ),
    ]
