# Generated by Django 2.2.1 on 2019-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0046_consumertimeperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumertimeperiod',
            options={'ordering': ['-end', '-start']},
        ),
        migrations.AlterModelOptions(
            name='stresstest',
            options={'ordering': ['-resource__creation_time']},
        ),
        migrations.AddField(
            model_name='resource',
            name='allow_review_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Allow students to review attempts from'),
        ),
    ]
