# Generated by Django 2.2.4 on 2019-11-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0048_ltiuserdata_is_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonsumer',
            name='identifier_field',
            field=models.CharField(blank=True, choices=[('username', 'Username'), ('email', 'Email address'), ('', 'None')], default='', max_length=20, verbose_name='Field used to identify students'),
        ),
    ]
