# Generated by Django 2.2.4 on 2019-11-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0050_ltiuserdata_lis_person_sourcedid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuserdata',
            name='lis_person_sourcedid',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
