# Generated by Django 2.2.4 on 2019-11-12 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numbas_lti', '0051_auto_20191107_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTILaunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(max_length=500)),
                ('ip_address', models.CharField(max_length=100)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='numbas_lti.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_launches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='AttemptLaunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(max_length=100)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='numbas_lti.Attempt')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
