# Generated by Django 2.2.4 on 2019-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0052_attemptlaunch_ltilaunch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='receipt_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time the completion receipt was sent'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='sent_receipt',
            field=models.BooleanField(default=False, verbose_name='Has a completion receipt been sent?'),
        ),
    ]
