# Generated by Django 2.2.4 on 2019-12-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0053_auto_20191121_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='email_receipts',
            field=models.BooleanField(default=False, verbose_name='Email attempt receipts to students on completion?'),
        ),
    ]
