# Generated by Django 2.2.10 on 2020-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0054_resource_email_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Available from'),
        ),
        migrations.AddField(
            model_name='resource',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Available until'),
        ),
    ]
