# Generated by Django 2.2.10 on 2020-04-01 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numbas_lti', '0055_auto_20200331_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptlaunch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt_launches', to=settings.AUTH_USER_MODEL),
        ),
    ]
