# Generated by Django 2.2.10 on 2020-04-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0056_attemptlaunch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='show_marks_when',
            field=models.CharField(choices=[('always', 'Always'), ('complete', 'When attempt is complete'), ('review', 'When review is allowed'), ('never', 'Never')], default='always', max_length=20, verbose_name='When to show scores to students'),
        ),
    ]
