# Generated by Django 2.2.10 on 2020-05-21 08:28

from django.db import migrations, models

def set_all_data_received(apps, schema_editor):
    Attempt = apps.get_model('numbas_lti','Attempt')

    for attempt in Attempt.objects.all():
        if attempt.completion_status=='completed':
            attempt.all_data_received = True
            attempt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0057_auto_20200430_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='all_data_received',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_all_data_received,migrations.RunPython.noop),
    ]
