# Generated by Django 2.2.13 on 2020-12-07 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numbas_lti', '0058_attempt_all_data_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkedScormElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remarked', to='numbas_lti.ScormElement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarked_elements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
