# Generated by Django 2.2.13 on 2021-01-18 08:31

from django.conf import settings
from django.db import migrations, models
import uuid
import os
import shutil

def move_to_uuid_folder(apps, schema_editor):
    Exam = apps.get_model('numbas_lti', 'Exam')

    for exam in Exam.objects.all():
        exam.static_uuid = uuid.uuid4()
        exam.save()
        old_path = os.path.join(os.getcwd(), settings.MEDIA_ROOT,'extracted_zips',exam.__class__.__name__,str(exam.pk))
        new_path = os.path.join(os.getcwd(), settings.MEDIA_ROOT,'extracted_zips',exam.__class__.__name__,str(exam.static_uuid))
        if os.path.exists(old_path):
            shutil.move(old_path, new_path)

def undo_move_to_uuid_folder(apps, schema_editor):
    Exam = apps.get_model('numbas_lti', 'Exam')

    for exam in Exam.objects.all():
        old_path = os.path.join(os.getcwd(), settings.MEDIA_ROOT,'extracted_zips',exam.__class__.__name__,str(exam.pk))
        new_path = os.path.join(os.getcwd(), settings.MEDIA_ROOT,'extracted_zips',exam.__class__.__name__,str(exam.static_uuid))
        if os.path.exists(new_path):
            shutil.move(new_path, old_path)

class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0060_auto_20201215_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='static_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID of exam package on disk'),
        ),
        migrations.RunPython(move_to_uuid_folder, undo_move_to_uuid_folder),
        migrations.AlterField(
            model_name='exam',
            name='static_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID of exam package on disk'),
        )
    ]
