# Generated by Django 2.2.13 on 2021-02-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0061_exam_static_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScormElementDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_of', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diffs', to='numbas_lti.ScormElement')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diff', to='numbas_lti.ScormElement')),
            ],
        ),
    ]
