# Generated by Django 2.2.13 on 2021-03-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0063_auto_20210211_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'verbose_name': 'access token', 'verbose_name_plural': 'access tokens'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-start_time'], 'verbose_name': 'attempt', 'verbose_name_plural': 'attempts'},
        ),
        migrations.AlterModelOptions(
            name='attemptlaunch',
            options={'ordering': ('-time',), 'verbose_name': 'attempt launch', 'verbose_name_plural': 'attempt launches'},
        ),
        migrations.AlterModelOptions(
            name='attemptquestionscore',
            options={'verbose_name': 'question score', 'verbose_name_plural': 'question scores'},
        ),
        migrations.AlterModelOptions(
            name='consumertimeperiod',
            options={'ordering': ['-end', '-start'], 'verbose_name': 'time period', 'verbose_name_plural': 'time periods'},
        ),
        migrations.AlterModelOptions(
            name='discountpart',
            options={'verbose_name': 'discounted part', 'verbose_name_plural': 'discounted parts'},
        ),
        migrations.AlterModelOptions(
            name='editorlink',
            options={'verbose_name': 'editor link', 'verbose_name_plural': 'editor links'},
        ),
        migrations.AlterModelOptions(
            name='editorlinkproject',
            options={'ordering': ['name'], 'verbose_name': 'linked editor project', 'verbose_name_plural': 'linked editor project'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-creation_time', 'title'], 'verbose_name': 'exam', 'verbose_name_plural': 'exams'},
        ),
        migrations.AlterModelOptions(
            name='lticonsumer',
            options={'verbose_name': 'LTI consumer', 'verbose_name_plural': 'LTI consumers'},
        ),
        migrations.AlterModelOptions(
            name='lticontext',
            options={'verbose_name': 'LTI context', 'verbose_name_plural': 'LTI contexts'},
        ),
        migrations.AlterModelOptions(
            name='ltilaunch',
            options={'ordering': ('-time',), 'verbose_name': 'LTI launch', 'verbose_name_plural': 'LTI launches'},
        ),
        migrations.AlterModelOptions(
            name='ltiuserdata',
            options={'verbose_name': 'LTI user data', 'verbose_name_plural': 'LTI user data'},
        ),
        migrations.AlterModelOptions(
            name='remarkedscormelement',
            options={'verbose_name': 'remarked SCORM element', 'verbose_name_plural': 'remarked SCORM element'},
        ),
        migrations.AlterModelOptions(
            name='remarkpart',
            options={'verbose_name': 'remarked part', 'verbose_name_plural': 'remarked parts'},
        ),
        migrations.AlterModelOptions(
            name='reportprocess',
            options={'ordering': ['-time'], 'verbose_name': 'report process', 'verbose_name_plural': 'report processes'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-creation_time', 'title'], 'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelOptions(
            name='scormelement',
            options={'ordering': ['-time', '-counter'], 'verbose_name': 'SCORM element', 'verbose_name_plural': 'SCORM elements'},
        ),
        migrations.AlterModelOptions(
            name='scormelementdiff',
            options={'verbose_name': 'SCORM element diff', 'verbose_name_plural': 'SCORM element diffs'},
        ),
        migrations.AlterModelOptions(
            name='stresstest',
            options={'ordering': ['-resource__creation_time'], 'verbose_name': 'stress test', 'verbose_name_plural': 'stress tests'},
        ),
        migrations.AlterModelOptions(
            name='stresstestnote',
            options={'verbose_name': 'stress test note', 'verbose_name_plural': 'stress test notes'},
        ),
    ]
