# Generated by Django 2.2.13 on 2021-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0066_auto_20210513_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesschange',
            name='extend_duration_units',
            field=models.CharField(blank=True, choices=[('percent', 'percent'), ('minutes', 'minutes')], default='percent', max_length=10, null=True),
        ),
    ]
