# Generated by Django 3.2.7 on 2021-09-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0067_auto_20210513_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarkpart',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
