# Generated by Django 3.2.12 on 2022-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0072_alter_editorlink_last_cache_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='require_lockdown_app',
            field=models.BooleanField(default=False, verbose_name='Require the lockdown app?'),
        ),
    ]
