# Generated by Django 3.2.15 on 2023-02-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0073_resource_require_lockdown_app_squashed_0075_auto_20221018_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuserdata',
            name='lis_person_sourcedid',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ltiuserdata',
            name='lis_result_sourcedid',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
