# Generated by Django 3.2.14 on 2022-10-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0073_resource_require_lockdown_app'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lticontext',
            unique_together={('context_id', 'instance_guid')},
        ),
    ]
