# Generated by Django 3.2.16 on 2023-10-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0074_auto_20230227_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesschange',
            name='disable_duration',
            field=models.BooleanField(default=False, verbose_name='Disable time limit?'),
        ),
    ]
