# Generated by Django 3.2.16 on 2024-02-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0075_accesschange_disable_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesschange',
            name='lockdown_app_password',
            field=models.CharField(blank=True, max_length=30, verbose_name='Password for the Numbas lockdown app'),
        ),
        migrations.AddField(
            model_name='accesschange',
            name='require_lockdown_app',
            field=models.CharField(blank=True, choices=[('unchanged', 'Unchanged'), ('', 'No'), ('numbas', 'Numbas lockdown app'), ('seb', 'Safe Exam Browser')], default='unchanged', max_length=20, verbose_name='Require a lockdown app?'),
        ),
        migrations.AddField(
            model_name='accesschange',
            name='seb_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_changes', to='numbas_lti.sebsettings'),
        ),
    ]
