# Generated by Django 3.2.16 on 2023-10-26 09:08

from django.db import migrations, models
import django.db.models.deletion

def lti_11_consumers(apps, schema_editor):
    LTIConsumer = apps.get_model('numbas_lti', 'LTIConsumer')
    LTI_11_Consumer = apps.get_model('numbas_lti', 'LTI_11_Consumer')

    for c in LTIConsumer.objects.all():
        LTI_11_Consumer.objects.create(
            consumer=c,
            key=c.key,
            secret=c.secret
        )

class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0075_accesschange_disable_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTI_11_Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key should be human-readable, and uniquely identify this consumer.', max_length=100, unique=True, verbose_name='Consumer key')),
                ('secret', models.CharField(max_length=100, verbose_name='Shared secret')),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lti_11', to='numbas_lti.lticonsumer')),
            ],
        ),
        
        migrations.RunPython(lti_11_consumers, migrations.RunPython.noop),
    ]
