# Generated by Django 3.2.16 on 2023-10-27 13:01

from django.db import migrations, models
import django.db.models.deletion

def make_lti_11_resource_links(apps, schema_editor):
    Resource = apps.get_model('numbas_lti', 'Resource')
    LTI_11_ResourceLink = apps.get_model('numbas_lti', 'LTI_11_ResourceLink')

    for r in Resource.objects.all():
        LTI_11_ResourceLink.objects.create(resource=r, resource_link_id=r.resource_link_id, context=r.context)

class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0079_auto_20231026_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_going', to='numbas_lti.lticontext'),
        ),
        migrations.CreateModel(
            name='LTI_11_ResourceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link_id', models.CharField(max_length=300)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='numbas_lti.lticontext')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_11_links', to='numbas_lti.resource')),
            ],
        ),
        migrations.RunPython(make_lti_11_resource_links, migrations.RunPython.noop)
    ]
