# Generated by Django 3.2.16 on 2023-10-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0081_auto_20231027_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='context',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_link_id',
        ),
    ]
