# Generated by Django 3.2.16 on 2023-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0082_auto_20231027_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lti_13_resourcelink',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
