# Generated by Django 3.2.16 on 2023-12-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0083_alter_lti_13_resourcelink_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltilaunch',
            name='lti_11_resource_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launches', to='numbas_lti.lti_11_resourcelink'),
        ),
        migrations.AddField(
            model_name='ltilaunch',
            name='lti_13_resource_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launches', to='numbas_lti.lti_13_resourcelink'),
        ),
        migrations.AddField(
            model_name='ltilaunch',
            name='role',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('teacher', 'Teacher'), ('student', 'Student')], default='', max_length=20),
        ),
    ]
