# Generated by Django 3.2.16 on 2023-12-15 11:17

from django.db import migrations, models
import django.db.models.deletion

def move_lti_11_userdata(apps, schema_editor):
    LTIUserData = apps.get_model('numbas_lti', 'LTIUserData')
    LTI_11_UserData = apps.get_model('numbas_lti', 'LTI_11_UserData')

    for ud in LTIUserData.objects.all():
        LTI_11_UserData.objects.create(
            user_data=ud,
            lis_result_sourcedid=ud.lis_result_sourcedid,
            lis_outcome_service_url=ud.lis_outcome_service_url,
            lis_person_sourcedid=ud.lis_person_sourcedid
        )

class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0084_auto_20231207_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTI_11_UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lis_result_sourcedid', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('lis_outcome_service_url', models.TextField(blank=True, default='', null=True)),
                ('lis_person_sourcedid', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lti_11', to='numbas_lti.ltiuserdata')),
            ],
        ),
        migrations.RunPython(move_lti_11_userdata, migrations.RunPython.noop),
        migrations.RemoveField(model_name='ltiuserdata', name='lis_result_sourcedid'),
        migrations.RemoveField(model_name='ltiuserdata', name='lis_outcome_service_url'),
        migrations.RemoveField(model_name='ltiuserdata', name='lis_person_sourcedid'),
    ]
