# Generated by Django 3.2.16 on 2023-12-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0085_lti_11_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTI_13_Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ags_data', models.JSONField(blank=True, default=dict, null=True)),
                ('context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lti_13', to='numbas_lti.lticontext')),
            ],
        ),
    ]
