# Generated by Django 5.0 on 2024-01-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0086_lti_13_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='lti_13_context',
            name='nrps_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
