# Generated by Django 5.0 on 2024-03-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0087_lti_13_context_nrps_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lticontext',
            unique_together={('context_id', 'instance_guid', 'consumer')},
        ),
    ]
