# Generated by Django 5.0.6 on 2024-05-22 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0088_alter_lticontext_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIConsumerRegistrationToken',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500, verbose_name='Intended use for this token')),
            ],
        ),
    ]
