# Generated by Django 5.0.6 on 2024-05-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0076_auto_20240208_1320'),
        ('numbas_lti', '0089_lticonsumerregistrationtoken'),
    ]

    operations = [
    ]
