# Generated by Django 5.0.6 on 2024-05-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0090_merge_20240530_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lticonsumerregistrationtoken',
            options={'verbose_name': 'LTI consumer registration token', 'verbose_name_plural': 'LTI consumer registration tokens'},
        ),
    ]
