# Generated by Django 5.0.7 on 2024-07-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0092_resource_lineitem_unwanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Before this time, students may not start or resume attempts.', null=True, verbose_name='Available from'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Attempts will end automatically at this time and students may not resume or start new attempts. Students may review existing attempts after this time.', null=True, verbose_name='Available until'),
        ),
    ]
