# Generated by Django 5.0.6 on 2024-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0092_resource_lineitem_unwanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesschange',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AddField(
            model_name='resource',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due date'),
        ),
    ]
