# Generated by Django 5.0.7 on 2024-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0093_alter_resource_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lti_13_context',
            name='cached_lineitems',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='lti_13_context',
            name='lineitems_last_fetched',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last time line AGS items fetched'),
        ),
    ]
