# Generated by Django 5.0.7 on 2024-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0094_lti_13_context_cached_lineitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesschange',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AddField(
            model_name='resource',
            name='allow_student_reopen',
            field=models.BooleanField(default=True, verbose_name='Allow students to re-open attempts while the resource is available?'),
        ),
        migrations.AddField(
            model_name='resource',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='At this time, any open attempts will automatically end. Students may review existing attempts or re-open them while the resource is available.', null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='completion_status',
            field=models.CharField(choices=[('not attempted', 'Not started'), ('incomplete', 'In progress'), ('completed', 'Complete')], default='not attempted', max_length=20),
        ),
    ]
