# Generated by Django 5.1.4 on 2025-02-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0099_alter_resource_allow_student_reopen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('show_total_score', models.CharField(choices=[('none', "Don't show a total score"), ('scaled', 'Add scaled scores'), ('raw', 'Add raw scores'), ('completion', 'Number of resources completed'), ('max_scores', 'Number of resources with maximum score')], default='none', max_length=10, verbose_name='Show a total score?')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='numbas_lti.lticontext')),
            ],
        ),
        migrations.CreateModel(
            name='ContextSummaryResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('context_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numbas_lti.contextsummary')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='numbas_lti.resource')),
            ],
            options={
                'ordering': ('order', 'resource'),
            },
        ),
        migrations.AddField(
            model_name='contextsummary',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='context_summaries', through='numbas_lti.ContextSummaryResource', to='numbas_lti.resource'),
        ),
    ]
