# Generated by Django 5.1.4 on 2025-04-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0099_alter_resource_allow_student_reopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lti_13_useralias',
            name='lis_person_sourcedid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
