# Generated by Django 5.1.4 on 2025-08-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0100_lti_13_useralias_lis_person_sourcedid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscorereported',
            name='completion_status',
            field=models.CharField(blank=True, choices=[('not attempted', 'Not started'), ('incomplete', 'In progress'), ('completed', 'Complete')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userscorereported',
            name='max_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscorereported',
            name='raw_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userscorereported',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
