# Generated by Django 5.1.4 on 2025-02-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0101_contextsummary_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextsummary',
            name='show_due_dates',
            field=models.BooleanField(default=False, verbose_name='Show due dates?'),
        ),
    ]
