# Generated by Django 6.0.2 on 2026-02-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0101_alter_userscorereported_completion_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_tags', models.JSONField(blank=True, default=dict, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='numbas_lti.exam')),
            ],
        ),
    ]
