# Generated by Django 5.1.4 on 2025-02-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0102_contextsummary_show_due_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextsummary',
            name='show_header',
            field=models.BooleanField(default=True, verbose_name='Show header?'),
        ),
    ]
