# Generated by Django 5.1.4 on 2025-08-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0101_alter_userscorereported_completion_status_and_more'),
        ('numbas_lti', '0103_contextsummary_show_header'),
    ]

    operations = [
    ]
