# Generated by Django 5.1.4 on 2025-04-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0100_lti_13_useralias_lis_person_sourcedid'),
        ('numbas_lti', '0103_contextsummary_show_header'),
    ]

    operations = [
    ]
