# Generated by Django 5.1.4 on 2025-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0104_merge_20250826_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contextsummaryresource',
            options={'ordering': ('group_order', 'order', 'resource')},
        ),
        migrations.AddField(
            model_name='contextsummaryresource',
            name='group',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contextsummaryresource',
            name='group_order',
            field=models.IntegerField(default=0),
        ),
    ]
