# Generated by Django 6.0.2 on 2026-03-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbas_lti', '0102_examanalysis'),
        ('numbas_lti', '0105_alter_contextsummaryresource_options_and_more'),
    ]

    operations = [
    ]
