# Generated by Django 6.0.2 on 2026-03-27 10:18

import django.db.models.deletion
import ncl_data_science.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numbas_lti', '0106_merge_20260317_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ncl_data_science/topics')),
            ],
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('difficulty', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ncl_data_science/case_studies')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_science_case_studies', to='numbas_lti.resource')),
            ],
            options={
                'verbose_name': 'Case study',
                'verbose_name_plural': 'Case studies',
            },
            bases=(models.Model, ncl_data_science.models.HasProgressMixin),
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_science_subtopics', to='numbas_lti.resource')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='ncl_data_science.topic')),
            ],
            bases=(models.Model, ncl_data_science.models.HasProgressMixin),
        ),
        migrations.CreateModel(
            name='CaseStudyTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_extension', models.BooleanField(default=False)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncl_data_science.casestudy')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncl_data_science.topic')),
            ],
        ),
        migrations.AddField(
            model_name='casestudy',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='case_studies', through='ncl_data_science.CaseStudyTopic', to='ncl_data_science.topic'),
        ),
    ]
