# Generated by Django 6.0.2 on 2026-03-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncl_data_science', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'verbose_name': 'Case study', 'verbose_name_plural': 'Case studies'},
        ),
    ]
