# Generated by Django 6.0.2 on 2026-03-04 15:43

import django.db.models.deletion
import student_files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('numbas_lti', '0102_examanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=student_files.models.student_file_upload_to)),
                ('part', models.CharField(max_length=50)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='numbas_lti.attempt')),
            ],
        ),
    ]
